name: flutter4
description: Une application Flutter Cooking avec Firebase.

version: 1.0.0+1

environment:
   sdk: ^3.6.0  # ✅ Ajout de la contrainte Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.1
  #cloud_firestore: ^4.14.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  












#name: flutter1
#description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
#version: 1.0.0+1

#environment:
#  sdk: ^3.6.0

#dependencies:
 # flutter:
#    sdk: flutter
#  firebase_auth: ^4.6.0
#  cloud_firestore: ^5.3.0
 # firebase_core: ^3.8.0
 # cupertino_icons: ^1.0.8

#dev_dependencies:
#  flutter_test:
 #   sdk: flutter
#  flutter_lints: ^5.0.0

#flutter:
#  uses-material-design: true
